export type RoleType = "technical" | "non_technical";

export interface RoleOption {
  name: string;
  type: RoleType;
}

// Single source of truth for selectable roles across the app (quiz creation, role select combobox).
// `type` drives frontend behavior: non_technical roles hide tech-stack input, require a document
// upload, and relabel the question-type split as Theory vs Practical Scenario.
export const ROLES: RoleOption[] = [
  { name: "Python Developer", type: "technical" },
  { name: "Java Developer", type: "technical" },
  { name: "JavaScript Developer", type: "technical" },
  { name: "TypeScript Developer", type: "technical" },
  { name: "C Developer", type: "technical" },
  { name: "C++ Developer", type: "technical" },
  { name: "C# Developer", type: "technical" },
  { name: "Go Developer", type: "technical" },
  { name: "Rust Developer", type: "technical" },
  { name: "Ruby Developer", type: "technical" },
  { name: "PHP Developer", type: "technical" },
  { name: "Swift Developer", type: "technical" },
  { name: "Kotlin Developer", type: "technical" },
  { name: "Scala Developer", type: "technical" },
  { name: "Perl Developer", type: "technical" },
  { name: "Haskell Developer", type: "technical" },
  { name: "MATLAB Developer", type: "technical" },
  { name: "R Developer", type: "technical" },
  { name: "SQL Developer", type: "technical" },
  { name: "HTML Developer", type: "technical" },
  { name: "CSS Developer", type: "technical" },
  { name: "React Developer", type: "technical" },
  { name: "Angular Developer", type: "technical" },
  { name: "Vue Developer", type: "technical" },
  { name: "Svelte Developer", type: "technical" },
  { name: "Django Developer", type: "technical" },
  { name: "Flask Developer", type: "technical" },
  { name: "FastAPI Developer", type: "technical" },
  { name: "Spring Developer", type: "technical" },
  { name: "Express Developer", type: "technical" },
  { name: "NextJS Developer", type: "technical" },
  { name: "NestJS Developer", type: "technical" },
  { name: ".NET Developer", type: "technical" },
  { name: "Bootstrap Developer", type: "technical" },
  { name: "Tailwind CSS Developer", type: "technical" },
  { name: "jQuery Developer", type: "technical" },
  { name: "Docker Engineer", type: "technical" },
  { name: "Kubernetes Engineer", type: "technical" },
  { name: "Terraform Engineer", type: "technical" },
  { name: "Ansible Engineer", type: "technical" },
  { name: "Jenkins Engineer", type: "technical" },
  { name: "Git Specialist", type: "technical" },
  { name: "GitHub Specialist", type: "technical" },
  { name: "GitLab Specialist", type: "technical" },
  { name: "CI CD Engineer", type: "technical" },
  { name: "PostgreSQL Developer", type: "technical" },
  { name: "MySQL Developer", type: "technical" },
  { name: "MongoDB Developer", type: "technical" },
  { name: "Redis Developer", type: "technical" },
  { name: "SQLite Developer", type: "technical" },
  { name: "Oracle Database Developer", type: "technical" },
  { name: "DynamoDB Developer", type: "technical" },
  { name: "Firebase Developer", type: "technical" },
  { name: "Supabase Developer", type: "technical" },
  { name: "AWS Cloud Engineer", type: "technical" },
  { name: "Azure Cloud Engineer", type: "technical" },
  { name: "GCP Cloud Engineer", type: "technical" },
  { name: "Compiler Engineer", type: "technical" },
  { name: "Interpreter Engineer", type: "technical" },
  { name: "Operating System Engineer", type: "technical" },
  { name: "Linux Engineer", type: "technical" },
  { name: "Unix Engineer", type: "technical" },
  { name: "Bash Engineer", type: "technical" },
  { name: "Shell Scripting Engineer", type: "technical" },
  { name: "Command Line Engineer", type: "technical" },
  { name: "API Developer", type: "technical" },
  { name: "Software Engineer", type: "technical" },
  { name: "Associate Software Engineer (ASE)", type: "technical" },
  { name: "Associate Software Engineer (Open Stack)", type: "technical" },

  { name: "Frontend Developer", type: "technical" },
  { name: "Backend Developer", type: "technical" },
  { name: "Full Stack Developer", type: "technical" },
  { name: "Mobile App Developer", type: "technical" },
  { name: "Android Developer", type: "technical" },
  { name: "iOS Developer", type: "technical" },
  { name: "Flutter Developer", type: "technical" },
  { name: "React Native Developer", type: "technical" },
  { name: "MERN Stack Developer", type: "technical" },
  { name: "MEAN Stack Developer", type: "technical" },
  { name: "Laravel Developer", type: "technical" },
  { name: "ASP.NET Developer", type: "technical" },
  { name: "Node.js Developer", type: "technical" },
  { name: "Machine Learning Engineer", type: "technical" },
  { name: "AI Engineer", type: "technical" },
  { name: "Generative AI Engineer", type: "technical" },
  { name: "Data Engineer", type: "technical" },
  { name: "Data Scientist", type: "technical" },
  { name: "Data Analyst", type: "technical" },
  { name: "QA Engineer", type: "technical" },
  { name: "Software QA Engineer", type: "technical" },
  { name: "Automation QA Engineer", type: "technical" },
  { name: "Manual QA Engineer", type: "technical" },
  { name: "Test Engineer", type: "technical" },
  { name: "SDET (Software Development Engineer in Test)", type: "technical" },
  { name: "DevOps Engineer", type: "technical" },
  { name: "Site Reliability Engineer (SRE)", type: "technical" },
  { name: "Platform Engineer", type: "technical" },
  { name: "Security Engineer", type: "technical" },
  { name: "Cyber Security Engineer", type: "technical" },
  { name: "Application Security Engineer", type: "technical" },
  { name: "Network Engineer", type: "technical" },
  { name: "Systems Engineer", type: "technical" },
  { name: "Embedded Systems Engineer", type: "technical" },
  { name: "Firmware Engineer", type: "technical" },
  { name: "Blockchain Developer", type: "technical" },
  { name: "Game Developer", type: "technical" },
  { name: "AR/VR Developer", type: "technical" },
  { name: "BI Developer", type: "technical" },
  { name: "CRM Developer", type: "technical" },
  { name: "Salesforce Developer", type: "technical" },
  { name: "Microsoft Dynamics 365 Developer", type: "technical" },
  { name: "SAP Developer", type: "technical" },
  { name: "Integration Engineer", type: "technical" },
  { name: "Solutions Architect", type: "technical" },
  { name: "Cloud Architect", type: "technical" },
  { name: "Enterprise Architect", type: "technical" },
  { name: "Database Administrator (DBA)", type: "technical" },
  { name: "Release Engineer", type: "technical" },
  { name: "Build Engineer", type: "technical" },
  { name: "Performance Engineer", type: "technical" },
  { name: "Senior Software Engineer", type: "technical" },
  { name: "Lead Software Engineer", type: "technical" },
  { name: "Principal Software Engineer", type: "technical" },
  { name: "Staff Software Engineer", type: "technical" },
  { name: "Engineering Manager", type: "technical" },
  { name: "Associate Team Lead", type: "technical" },
  { name: "Team Lead", type: "technical" },
  { name: "Technical Lead", type: "technical" },
  { name: "Engineering Director", type: "technical" },
  { name: "VP of Engineering", type: "technical" },
  { name: "Chief Technology Officer (CTO)", type: "technical" },

  // Non-technical roles — quiz is generated from an uploaded document instead of a tech stack.
  // Scoped to roles that actually exist inside a technology company (not generic
  // cross-industry roles like bank teller, pharmacist, real estate agent, etc.).
  { name: "HR Manager", type: "non_technical" },
  { name: "Recruiter / Talent Acquisition Specialist", type: "non_technical" },
  { name: "Technical Recruiter", type: "non_technical" },
  { name: "People Operations Manager", type: "non_technical" },
  { name: "Financial Analyst", type: "non_technical" },
  { name: "Accountant", type: "non_technical" },
  { name: "Compliance Officer", type: "non_technical" },
  { name: "Legal Counsel", type: "non_technical" },
  { name: "Risk Manager", type: "non_technical" },
  { name: "Internal Auditor", type: "non_technical" },
  { name: "Data Privacy Officer", type: "non_technical" },
  { name: "Marketing Manager", type: "non_technical" },
  { name: "Product Marketing Manager", type: "non_technical" },
  { name: "Growth Marketing Manager", type: "non_technical" },
  { name: "Demand Generation Manager", type: "non_technical" },
  { name: "Content Strategist", type: "non_technical" },
  { name: "Social Media Manager", type: "non_technical" },
  { name: "Brand Manager", type: "non_technical" },
  { name: "Public Relations Specialist", type: "non_technical" },
  { name: "Market Research Analyst", type: "non_technical" },
  { name: "Sales Manager", type: "non_technical" },
  { name: "Sales Representative", type: "non_technical" },
  { name: "Sales Development Representative (SDR)", type: "non_technical" },
  { name: "Account Executive", type: "non_technical" },
  { name: "Business Development Manager", type: "non_technical" },
  { name: "Partnerships Manager", type: "non_technical" },
  { name: "Solutions Consultant", type: "non_technical" },
  { name: "Sales Operations Manager", type: "non_technical" },
  { name: "Revenue Operations Manager", type: "non_technical" },
  { name: "Customer Success Manager", type: "non_technical" },
  { name: "Customer Support Lead", type: "non_technical" },
  { name: "Customer Onboarding Specialist", type: "non_technical" },
  { name: "Community Manager", type: "non_technical" },
  { name: "Product Manager", type: "non_technical" },
  { name: "Product Designer", type: "non_technical" },
  { name: "UX Designer", type: "non_technical" },
  { name: "UI Designer", type: "non_technical" },
  { name: "UX Researcher", type: "non_technical" },
  { name: "Graphic Designer", type: "non_technical" },
  { name: "Technical Writer", type: "non_technical" },
  { name: "Scrum Master", type: "non_technical" },
  { name: "Business Analyst", type: "non_technical" },
  { name: "Operations Manager", type: "non_technical" },
  { name: "Project Manager", type: "non_technical" },
  { name: "Chief of Staff", type: "non_technical" },
  { name: "Procurement Manager", type: "non_technical" },
  { name: "Supply Chain Manager", type: "non_technical" },
  { name: "Logistics Coordinator", type: "non_technical" },
  { name: "IT Support Specialist", type: "non_technical" },
  { name: "Localization Manager", type: "non_technical" },
  { name: "Administrative Manager", type: "non_technical" },
  { name: "Executive Assistant", type: "non_technical" },
  { name: "Office Manager", type: "non_technical" },
  { name: "Facilities Manager", type: "non_technical" },
  { name: "Purchasing Agent", type: "non_technical" },
  { name: "Event Manager", type: "non_technical" },
  { name: "Training & Development Specialist", type: "non_technical" },

  { name: "UI/UX Designer", type: "non_technical" },
  { name: "Visual Designer", type: "non_technical" },
  { name: "Interaction Designer", type: "non_technical" },
  { name: "Motion Designer", type: "non_technical" },
  { name: "Creative Designer", type: "non_technical" },
  { name: "QA Manager", type: "non_technical" },
  { name: "Delivery Manager", type: "non_technical" },
  { name: "Program Manager", type: "non_technical" },
  { name: "Technical Program Manager (TPM)", type: "non_technical" },
  { name: "PMO Manager", type: "non_technical" },
  { name: "Agile Coach", type: "non_technical" },
  { name: "Release Manager", type: "non_technical" },
  { name: "Customer Support Engineer", type: "non_technical" },
  { name: "Application Support Engineer", type: "non_technical" },
  { name: "Pre-Sales Engineer", type: "non_technical" },
  { name: "Sales Engineer", type: "non_technical" },
  { name: "Solutions Engineer", type: "non_technical" },
  { name: "Customer Experience Manager", type: "non_technical" },
  { name: "Client Success Manager", type: "non_technical" },
  { name: "Client Relationship Manager", type: "non_technical" },
  { name: "Account Manager", type: "non_technical" },
  { name: "Key Account Manager", type: "non_technical" },
  { name: "Customer Experience Specialist", type: "non_technical" },
  { name: "Implementation Consultant", type: "non_technical" },
  { name: "Implementation Engineer", type: "non_technical" },
  { name: "ERP Consultant", type: "non_technical" },
  { name: "Functional Consultant", type: "non_technical" },
  { name: "Technical Consultant", type: "non_technical" },
  { name: "AI Consultant", type: "non_technical" },
  { name: "Cloud Consultant", type: "non_technical" },
  { name: "Security Consultant", type: "non_technical" },
  { name: "Business Development Executive (BDE)", type: "non_technical" },
  { name: "Growth Executive", type: "non_technical" },
  { name: "Growth Manager", type: "non_technical" },
  { name: "Digital Marketing Specialist", type: "non_technical" },
  { name: "SEO Specialist", type: "non_technical" },
  { name: "SEM/PPC Specialist", type: "non_technical" },
  { name: "Email Marketing Specialist", type: "non_technical" },
  { name: "Copywriter", type: "non_technical" },
  { name: "Employer Branding Specialist", type: "non_technical" },
  { name: "Learning & Development Manager", type: "non_technical" },
  { name: "IT Administrator", type: "non_technical" },
  { name: "System Administrator", type: "non_technical" },
  { name: "Network Administrator", type: "non_technical" },
  { name: "Help Desk Engineer", type: "non_technical" },
  { name: "Vendor Manager", type: "non_technical" },
  { name: "Finance Manager", type: "non_technical" },
  { name: "Payroll Specialist", type: "non_technical" },
  { name: "Compensation & Benefits Specialist", type: "non_technical" },
  { name: "HR Business Partner (HRBP)", type: "non_technical" },
  { name: "Employer Relations Specialist", type: "non_technical" },
];

export const ROLE_NAMES = ROLES.map((r) => r.name);

export function getRoleType(roleName: string): RoleType {
  return ROLES.find((r) => r.name === roleName)?.type ?? "technical";
}

export function isNonTechnicalRole(roleName: string): boolean {
  return getRoleType(roleName) === "non_technical";
}
