export const TECHNOLOGIES = [
    "Python", "Java", "JavaScript", "TypeScript", "C", "C++", "C#", "Go", "Rust", "Ruby", "PHP",
    "Swift", "Kotlin", "Scala", "Perl", "Haskell", "MATLAB", "R", "SQL", "HTML5", "CSS3", "React", "Angular", "Vue", "Svelte", "Django", "Flask", "FastAPI",
    "Spring", "Express", "NextJS", "NestJS", "DotNet", ".NET", "Bootstrap", "Tailwind CSS", "jQuery",
    "MERN Stack", "MEAN Stack", "LAMP Stack", "JAMStack", "MEVN Stack",
    "Docker", "Kubernetes", "Terraform", "Ansible", "Jenkins", "Git", "GitHub", "GitLab", "CI/CD",
    "PostgreSQL", "MySQL", "MongoDB", "Redis", "SQLite", "Oracle", "DynamoDB", "Firebase", "Supabase",
    "Amazon Web Services (AWS)", "Microsoft Azure", "Google Cloud Platform (GCP)",
    "Compiler", "Interpreter", "Operating System", "Linux", "Unix", "Bash", "Shell", "Command Line", "API",
    "System Design", "Networking", "Database", "OOP", "DSA",
    "Node.js", "Maven", "GCC", "Make", "GDB", "CMake", "Cargo", "Ruby on Rails", "Laravel", "Xcode",
    "Redux", "Vuex", "Postman", "Vite", "Docker Compose", "Authentication", "Entity Framework", "Debugging", "Android",
    "Flutter", "Dart", "React Native", "ASP.NET",
    "Machine Learning", "Deep Learning", "TensorFlow", "PyTorch", "Pandas", "NumPy",
    "Generative AI", "LangChain", "Apache Spark", "Airflow",
    "Power BI", "Tableau", "Excel",
    "Selenium", "Test Automation", "Manual Testing", "JIRA",
    "Cybersecurity", "Penetration Testing",
    "Embedded Systems", "Microcontroller",
    "Blockchain", "Solidity",
    "Unity", "Unreal Engine",
    "Salesforce", "Microsoft Dynamics 365", "SAP"
].sort();
